<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Resources/asset/favicon.ico</ApplicationIcon>
    <AssemblyName>Doc Watcher</AssemblyName>
    <StartupObject>DocWatcher.Wpf.App</StartupObject>
    <Version>1.0.0</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.WinUI.Notifications" />
    <PackageReference Include="Markdig" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Velopack" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DocWatcher.Core\DocWatcher.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Resources\manuale.md" />
    <None Remove="Resources\asset\favicon.ico" />
    <None Remove="Resources\asset\ICO.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\manuale.md">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\asset\favicon.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\asset\ICO.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>
</Project>
